name: Build docs

on:
  push:
    branches:    
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_upload_docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install
        run: pip install .[docs]
      - name: Sphinx build
        run: make html
        working-directory: docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
