name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build twine
      - name: Build package
        run: python3 -m build
      - name: Upload package
        run: python3 -m twine upload dist/*
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
